before_script:
 - apt-get update -qq && apt-get install -y -qq inkscape python-dev python-pip
 - pip install --upgrade setuptools
 - pip install nose coverage
 - pip install -r requirements.txt
 - pip install -e .[tests,sphinx,images,svgsupport,aafiguresupport,mathsupport,rawhtmlsupport]

test:
  script:
  - nosetests -i regulartest -i sphinxtest --with-xunit
  artifacts:
    reports:
      junit: nosetests.xml
    paths:
    - rst2pdf/tests/output/*pdf
    expire_in: 1 week
    when: on_failure

