sudo: false

language: python
python:
 - 2.7

before_install:
 - pip install --upgrade setuptools
 - pip install nose coverage
 - pip install -r requirements.txt
 - python setup.py develop

script:
 - nosetests -i regulartest -i sphinxtest
