filter_secrets: false
os: linux
dist: xenial

addons:
  apt:
    packages:
    - inkscape
    - texlive-latex-base
    - dvipng

language: python
python:
 - 3.6
 - 3.7

before_install:
 - pip install --upgrade setuptools
 - pip install pytest
 - pip install -c requirements.txt -e .[tests,sphinx,images,svgsupport,aafiguresupport,mathsupport,rawhtmlsupport]

script:
 - pytest
