sudo: false
filter_secrets: false

addons:
  apt:
    packages:
    - inkscape

language: python
python:
 - 2.7

before_install:
 - pip install --upgrade setuptools
 - pip install nose coverage
 - pip install -r requirements.txt
 - pip install -e .[tests,sphinx,images,svgsupport,aafiguresupport,mathsupport,rawhtmlsupport]

script:
 - nosetests -i regulartest -i sphinxtest
