language: python
python:
- 2.7
- 3.5

before_install:
- pip install nose reportlab Pygments sphinx pillow pdfrw pyPdf Jinja2 coverage
- python setup.py install
- python bootstrap.py
- ./bin/buildout

script:
- ./bin/nosestests -i regulartest -i sphinxtest

